--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/creeperplayer20/C20s-TPALL
build-by-default: true
branches:
- main
projects:
  C20s-TPALL:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.0
...
