name: C20s-TpAll
version: 0.0.2
main: creeperplayer20\tpall\Main
author: creeperplayer20
api: 5.0.0

commands:
  tpall:
    description: "Teleport all online players to your current position."
    usage: "/tpall"
    permission: "c20s-tpall.use"
permissions:
  c20s-tpall.use:
    default: op
