name: TpAll
version: 0.0.1
main: creeperplayer20\tpall\Main
author: creeperplayer20
api: 4.0.8
src-namespace-prefix: creeperplayer20\tpall

commands:
    tpall:
        description: "Teleports every player on the server to you"
        usage: "/tpall"
        permission: "tpall.command"
permissions:
    tpall.command:
        default: op
