# § = color tag.
# {seconds} = represents the seconds before teleportation.

ui-title: "§6TpAll§r"

# sound:
# list of avaible sounds:
# Nothing, random.levelup, note.bass, note.hat, note.pling, note.snare, note.bd, note.harp, portal.travel
legacy-teleport-sound: "portal.travel"

# messages:
teleport-before-message: "{seconds} §cleft until teleport§f!"
teleport-after-message: "§gYou've been teleported§f!"
teleport-after-issuer-message: "§cPlayers have been teleported§f!"

no-players-online-message: "§cThere are no players online other than you§f!"
no-player-found-message: "§cPlayer not found§f!"

teleport-error-message: "§cAn error occurred while teleporting§f!"

tpall-task-is-running-message: "§cAnother TpAll task is already running§f!"

# reason:
reason-text: "§4====§r §f[§cTpAll§r§f] §4====§r\n§4§k!!!§r§3 Everyone on the server will be teleported§f!\n§4§k!!!§r§5 Reason§f: "
reason-default: "§uIt's event time§f!"

# number colors:
no-three-color: "§a"
no-two-color: "§e"
no-one-color: "§g"
no-zero-color: "§4"
no-default-color: "§6"
